(import ./osprey/router :prefix "" :export true)
(import ./osprey/helpers :prefix "" :export true)
(import ./osprey/form :prefix "form/" :export true)
(import ./osprey/multipart :prefix "multipart/" :export true)
(import janet-html :prefix "" :export true)

# convenience method for (use opsrey)
(def html/encode encode)
(def html/unsafe raw)
(def multipart? multipart/multipart?)
(def form? form/form?)
